- name: Installing Consul and Nomad on all nodes
  hosts: all
  tasks:
  - name: Installing gpg
    apt:
      name: gpg
      state: present
      update_cache: yes
    become: yes
  - name: Installing screen
    apt:
      name: screen
      state: present
      update_cache: yes
    become: yes
  - name: Installing wget
    apt:
      name: wget
      state: present
    become: yes
  - name: Adding Hashicorp apt repo
    block:
      - name: Downloading Hashicorp apt repo key
        shell: "wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg"
        args:
          creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - name: Adding Hashicorp apt repo
        shell: "echo \"deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main\" | sudo tee /etc/apt/sources.list.d/hashicorp.list"
        args:
          creates: /etc/apt/sources.list.d/hashicorp.list

    become: yes
  # - name: Installing Nomad
  #   apt:
  #     name: nomad
  #     state: present
  #     update_cache: yes
  #   become: yes
  - name: Installing Consul
    apt:
      name: consul
      state: present
      update_cache: yes
    become: yes
