- name: Installing Consul on all nodes
  hosts: all
  tasks:
  - name: Installing gpg
    apt:
      name: gpg
      state: present
      update_cache: yes
    become: yes
  - name: Installing lsb-release
    apt:
      name: lsb-release
      state: present
    become: yes
  - name: Installing wget
    apt:
      name: wget
      state: present
    become: yes
  - name: Adding Hashicorp apt repo
    block:
      - name: Downloading Hashicorp apt repo key
        shell: "wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg"
        args:
          creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - name: Adding Hashicorp apt repo
        shell: "echo \"deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main\" | tee /etc/apt/sources.list.d/hashicorp.list"
        args:
          creates: /etc/apt/sources.list.d/hashicorp.list

    become: yes
  - name: Installing Consul
    apt:
      name: consul
      state: present
      update_cache: yes
    become: yes


  - name: Adding GetEnvoy apt repo
    block:
      - name: Downloading GetEnvoy apt repo key
        shell: "wget -O- https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key | gpg --dearmor | tee /usr/share/keyrings/getenvoy.gpg"
        args:
          creates: /usr/share/keyrings/getenvoy.gpg
      - name: Adding GetEnvoy apt repo
        shell: "echo \"deb [arch=amd64 signed-by=/usr/share/keyrings/getenvoy.gpg] https://deb.dl.getenvoy.io/public/deb/ubuntu $(lsb_release -cs) main\" | tee /etc/apt/sources.list.d/getenvoy.list"
        args:
          creates: /etc/apt/sources.list.d/getenvoy.list

    become: yes
  - name: Installing Envoy
    apt:
      name: getenvoy-envoy
      state: present
      update_cache: yes
    become: yes
