# - name: Starting all Consul server agents
#   hosts: servers
#   tasks:
#   - name: Starting consul server agents
#     shell: "screen -dmS Consul_agent consul agent -config-file /etc/consul.d/server/config.hcl"
# - name: Starting all Consul client agents
#   hosts: clients
#   tasks:
#   - name: Starting consul client agents
#     shell: "screen -dmS Consul_agent consul agent -config-file /etc/consul.d/client/config.hcl"

- name: Starting Consul agents on all hosts
  hosts: servers:clients
  tasks:
  - name: Enabling and starting Consul service
    ansible.builtin.systemd:
      name: consul
      enabled: yes
      masked: no
      state: started
- name: Fetching Secret ID on one server
  hosts: dc1_server_1
  tasks:
  - name: Bootstrapping Consul cluster ACL
    command: "consul acl bootstrap -format=json"
    register: bootstrap_json
  - name: Display Consul DC SecretID
    debug:
      msg: "{{(bootstrap_json.stdout | from_json)['SecretID']}}"