test_vms:
  hosts:
    servertest:
      ansible_host: 192.168.122.99
      ansible_become_password: "toto"
      ubuntu_version: focal
test_containers:
  hosts: 
    master:
      ansible_host: 10.0.100.254
    client_1:
      ansible_host: 10.0.100.101
    client_2:
      ansible_host: 10.0.100.102
    client_3:
      ansible_host: 10.0.100.103
  vars:
    ansible_user: root
    ansible_password: password