# Data Center groups

dc1:
  hosts: 
    dc1_server_1:
      ansible_host: 10.33.1.1
    dc1_server_2:
      ansible_host: 10.33.1.2
    dc1_server_3:
      ansible_host: 10.33.1.3
    
    dc1_client_1:
      ansible_host: 10.33.1.101
    dc1_client_2:
      ansible_host: 10.33.1.102
    dc1_client_3:
      ansible_host: 10.33.1.103
  vars:
    ansible_user: root

dc2:
  hosts: 
    dc2_server_1:
      ansible_host: 10.33.2.1
    dc2_server_2:
      ansible_host: 10.33.2.2
    dc2_server_3:
      ansible_host: 10.33.2.3
      
    dc2_client_1:
      ansible_host: 10.33.2.101
    dc2_client_2:
      ansible_host: 10.33.2.102
    dc2_client_3:
      ansible_host: 10.33.2.103
  vars:
    ansible_user: root



# Servers & client groups


servers:
  hosts:
    dc1_server_1:
      ansible_host: 10.33.1.1
    dc1_server_2:
      ansible_host: 10.33.1.2
    dc1_server_3:
      ansible_host: 10.33.1.3

    dc2_server_1:
      ansible_host: 10.33.2.1
    dc2_server_2:
      ansible_host: 10.33.2.2
    dc2_server_3:
      ansible_host: 10.33.2.3


clients:
  hosts:
    dc1_client_1:
      ansible_host: 10.33.1.101
    dc1_client_2:
      ansible_host: 10.33.1.102
    dc1_client_3:
      ansible_host: 10.33.1.103

    dc2_client_1:
      ansible_host: 10.33.2.101
    dc2_client_2:
      ansible_host: 10.33.2.102
    dc2_client_3:
      ansible_host: 10.33.2.103